package enums;

public enum Subject {
	PEOM_L,
	PEOM_P,
	MATHEMATICAL_ANALISYS_L,
	MATHEMATICAL_ANALISYS_P,
	PHYSICAL_CULTURE,
	PHYSICAL_CULTURE_2,
	DISCRETE_MATHEMATICS_L,
	DISCRETE_MATHEMATICS_P,
	MOHYLA_STUDIES_L,
	MOHYLA_STUDIES_P,
	JAVA_L,
	JAVA_P,
	
	JAVA_SCRIPT_P,	
	HELL_OF_MYKHAILEVYCH_P,
	ARTIFICIAL_INTELLIGENCE_P,
	ARTIFICIAL_INTELLIGENCE_L,  
	HISTORY_OF_UKRAINIAN_CULTURE_P, 
	THEORY_OF_MANAGEMENT_L, 
	THEORY_OF_MANAGEMENT_P, 
	HELL_OF_MYKHAILEVYCH_L, 
	VIRUSOLOGY_L,
	VIRUSOLOGY_P,
	HISTORY_OF_UKRAINIAN_CULTURE_L,
	JAVA_SCRIPT_L, 
	GAP
}