
public enum Subject {
	JAVA_SCRIPT_P,
	JAVA_SCRIPT_L, 
	ARTIFICIAL_INTELLIGENCE_P,
	ARTIFICIAL_INTELLIGENCE_L,  
	HISTORY_OF_UKRAINIAN_CULTURE_L,
	HISTORY_OF_UKRAINIAN_CULTURE_P, 
	THEORY_OF_MANAGEMENT_L, 
	THEORY_OF_MANAGEMENT_P, 
	HELL_OF_MYKHAILEVYTCH_L, 
	HELL_OF_MYKHAILEVYTCH_P,
	VIRUSOLOGY_L,
	VIRUSOLOGY_P,
	GAP
}